main:
	gfortran checks.f90 decomposition.f90 LDLt.f90
	./a.out < data.dat > output.dat 2> errors.dat

show:
	gfortran checks.f90 decomposition.f90 LDLt.f90
	./a.out < data.dat > output.dat 2> errors.dat
	cat output.dat	
